version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: paredao-frontend
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
  
  redis:
    image: redis:7-alpine
    container_name: paredao-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  mysql:
    image: mysql:8.0
    container_name: paredao-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: paredao
      MYSQL_USER: paredao
      MYSQL_PASSWORD: paredao
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: paredao-api
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DB_USER: paredao
      DB_PASSWORD: paredao
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: paredao
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8080:8080"
      
  adminer:
    image: adminer:latest
    container_name: paredao-adminer
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: pepa-linha
      ADMINER_PLUGINS: tables-filter tinymce

volumes:
  mysql-data:
  redis-data:
